// This file is auto-generated by: pnpm run generate-types
// Run: supabase gen types typescript --local > packages/db/src/database.types.ts
// Do not edit manually.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      players: {
        Row: {
          id: string;
          email: string;
          username: string;
          full_name: string;
          gender: 'male' | 'female' | 'other';
          dob: string | null;
          photo_url: string | null;
          location: string | null;
          role: 'player' | 'organizer' | 'club_manager' | 'referee' | 'sponsor' | 'admin';
          is_provisional: boolean;
          provisional_expires_at: string | null;
          provisional_claim_token: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['players']['Row'], 'created_at' | 'updated_at'> & {
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['players']['Insert']>;
      };
      player_profiles: {
        Row: {
          player_id: string;
          bio: string | null;
          headline: string | null;
          career_history: Json;
          certifications: Json;
          playing_since: number | null;
          preferred_style: string | null;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['player_profiles']['Row'], 'updated_at'>;
        Update: Partial<Database['public']['Tables']['player_profiles']['Insert']>;
      };
      global_stats: {
        Row: {
          player_id: string;
          total_matches: number;
          wins: number;
          losses: number;
          win_rate: number;
          current_rating: number;
          peak_rating: number;
          singles_matches: number;
          singles_wins: number;
          doubles_matches: number;
          doubles_wins: number;
          mixed_doubles_matches: number;
          mixed_doubles_wins: number;
          updated_at: string;
        };
        Insert: Database['public']['Tables']['global_stats']['Row'];
        Update: Partial<Database['public']['Tables']['global_stats']['Insert']>;
      };
      clubs: {
        Row: {
          id: string;
          name: string;
          slug: string;
          logo_url: string | null;
          cover_url: string | null;
          brand_primary_color: string;
          brand_secondary_color: string;
          location: string | null;
          city: string | null;
          country: string | null;
          website: string | null;
          founding_year: number | null;
          description: string | null;
          subscription_tier: 'free' | 'starter' | 'pro' | 'enterprise';
          is_open_to_join: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['clubs']['Row'], 'created_at' | 'updated_at'> & {
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['clubs']['Insert']>;
      };
      club_affiliations: {
        Row: {
          id: string;
          player_id: string;
          club_id: string;
          is_current: boolean;
          joined_at: string;
          left_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['club_affiliations']['Row'], 'joined_at'> & {
          joined_at?: string;
        };
        Update: Partial<Database['public']['Tables']['club_affiliations']['Insert']>;
      };
      tournaments: {
        Row: {
          id: string;
          club_id: string;
          name: string;
          description: string | null;
          venue: string | null;
          start_date: string;
          end_date: string;
          status: 'draft' | 'registration_open' | 'in_progress' | 'completed' | 'cancelled';
          court_count: number;
          display_code: string;
          registration_deadline: string | null;
          max_participants: number | null;
          social_post_triggers: Json;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['tournaments']['Row'], 'created_at' | 'updated_at' | 'display_code'> & {
          display_code?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['tournaments']['Insert']>;
      };
      tournament_categories: {
        Row: {
          id: string;
          tournament_id: string;
          name: string;
          type: 'skill' | 'age' | 'gender' | 'open';
          play_format: 'singles' | 'doubles' | 'mixed_doubles';
          draw_format: 'round_robin' | 'single_elimination' | 'double_elimination' | 'group_stage_knockout' | 'swiss';
          status: 'pending' | 'registration' | 'draw_generated' | 'in_progress' | 'completed';
          max_entries: number | null;
          min_age: number | null;
          max_age: number | null;
          skill_levels: Json;
          winner_entry_id: string | null;
          runner_up_entry_id: string | null;
          third_place_entry_id: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['tournament_categories']['Row'], 'created_at'> & {
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['tournament_categories']['Insert']>;
      };
      tournament_entries: {
        Row: {
          id: string;
          tournament_id: string;
          category_id: string;
          player_id: string;
          partner_id: string | null;
          seed: number | null;
          status: 'active' | 'withdrawn' | 'provisional';
          registered_at: string;
        };
        Insert: Omit<Database['public']['Tables']['tournament_entries']['Row'], 'registered_at'> & {
          registered_at?: string;
        };
        Update: Partial<Database['public']['Tables']['tournament_entries']['Insert']>;
      };
      matches: {
        Row: {
          id: string;
          category_id: string;
          tournament_id: string;
          round: number;
          round_name: string | null;
          group_name: string | null;
          entry_a_id: string | null;
          entry_b_id: string | null;
          court: number | null;
          scheduled_time: string | null;
          status: 'scheduled' | 'in_progress' | 'completed' | 'disputed' | 'walkover' | 'retired';
          sets: Json;
          winner_entry_id: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['matches']['Row'], 'created_at'> & {
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['matches']['Insert']>;
      };
      match_history: {
        Row: {
          id: string;
          player_id: string;
          match_id: string;
          tournament_id: string;
          club_id: string;
          result: 'win' | 'loss' | 'walkover_win' | 'walkover_loss';
          sets: Json;
          opponent_entry_id: string | null;
          rating_before: number;
          rating_after: number;
          rating_change: number;
          played_at: string;
        };
        Insert: Database['public']['Tables']['match_history']['Row'];
        Update: Partial<Database['public']['Tables']['match_history']['Insert']>;
      };
      tournament_referee_pins: {
        Row: {
          id: string;
          tournament_id: string;
          pin_hash: string;
          label: string | null;
          created_by: string;
          created_at: string;
          expires_at: string;
          is_revoked: boolean;
        };
        Insert: Omit<Database['public']['Tables']['tournament_referee_pins']['Row'], 'created_at'> & {
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['tournament_referee_pins']['Insert']>;
      };
      display_state: {
        Row: {
          tournament_id: string;
          current_slide: string;
          is_pinned: boolean;
          rotation_interval_secs: number;
          active_announcement_id: string | null;
          active_category_filter: string | null;
          is_paused: boolean;
          last_updated_by: string | null;
          updated_at: string;
        };
        Insert: Database['public']['Tables']['display_state']['Row'];
        Update: Partial<Database['public']['Tables']['display_state']['Insert']>;
      };
      announcements: {
        Row: {
          id: string;
          tournament_id: string;
          message: string;
          urgency: 'normal' | 'urgent';
          sent_by: string;
          sent_at: string;
          dismissed_at: string | null;
          also_push_notify: boolean;
        };
        Insert: Omit<Database['public']['Tables']['announcements']['Row'], 'sent_at'> & {
          sent_at?: string;
        };
        Update: Partial<Database['public']['Tables']['announcements']['Insert']>;
      };
    };
    Views: Record<string, never>;
    Functions: {
      check_username_available: {
        Args: { p_username: string };
        Returns: boolean;
      };
      generate_display_code: {
        Args: Record<string, never>;
        Returns: string;
      };
      verify_referee_pin: {
        Args: { p_tournament_id: string; p_pin: string };
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
  };
}
